Fix error handling.
Fixes: commit d03b291c899ae4b461ebb57d7e535592df825ff2

Fixes:

    $ ttyjack hello < /dev/null
    Traceback (most recent call last):
      File ".../ttyjack", line 22, in push_fd
        fcntl.ioctl(fd, termios.TIOCSTI, s[0])
    OSError: [Errno 25] Inappropriate ioctl for device

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File ".../ttyjack", line 101, in <module>
        main()
      File ".../ttyjack", line 98, in main
        method(cmdline)
      File ".../ttyjack", line 32, in push
        push_fd(fd, s)
      File ".../ttyjack", line 24, in push_fd
        exc.__cause__ = early_io_error
    TypeError: exception cause must be None or derive from BaseException